# Generated by Django 3.0.7 on 2020-06-28 17:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Letra',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('letra', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Termino',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('termino', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now)),
                ('letra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionario.Letra')),
            ],
        ),
        migrations.CreateModel(
            name='Definicion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('definicion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name=datetime.datetime.now)),
                ('termino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diccionario.Termino')),
            ],
        ),
    ]
